<script>
		import {navigate} from 'svelte-routing';
	export let page = '1';
	let players = [], metadata = {}, search = '', loading = true, error = '';
	$: pageNumber = Math.max(1, parseInt(page || '1', 10) || 1);
	$: filtered = search.trim() ? players.filter(p => `${p.name} ${p.country}`.toLowerCase().includes(search.trim().toLowerCase())) : players;
	async function load(){loading=true;error='';try{const r=await fetch(`/api/scoresaber/v2/players?page=${pageNumber}&limit=50&sort=rank&sortDirection=asc`);if(!r.ok)throw Error(`ScoreSaber returned ${r.status}`);const j=await r.json();players=Array.isArray(j?.data)?j.data:[];metadata=j?.metadata||{};}catch(e){error=e.message||'Failed to load rankings.'}finally{loading=false}}
	let loadedPage = 0;
	$: if (pageNumber !== loadedPage) { loadedPage = pageNumber; load(); }
	function player(p){navigate(`/u/${p.id||p.playerId}`)}
</script>
<svelte:head><title>snore saber</title></svelte:head>
<div class="page"><div class="heading"><div><span class="eyebrow">SNORE SABER RANKINGS</span><h1>Global Ranking</h1><p>ScoreSaber rankings presented through the SnoreSaber interface.</p></div><div class="controls"><input bind:value={search} placeholder="Filter this page…" /><button on:click={load}>Refresh</button></div></div>
{#if loading}<div class="state">Loading live rankings…</div>{:else if error}<div class="state error">{error}<button on:click={load}>Retry</button></div>{:else}<div class="table"><div class="thead"><span>#</span><span>Player</span><span>Country</span><span>PP</span><span>Rank</span></div>{#each filtered as p,i}<button class="tr" on:click={() => player(p)}><span>{p.rank || ((pageNumber-1)*50+i+1)}</span><span class="player"><img src={p.avatar||'/assets/snoresaber-icon.png'} alt="" /><strong>{p.name||p.playerNameInGame}</strong></span><span>{p.country||'—'}</span><span>{Number(p.pp||0).toFixed(2)}</span><span class="rank-pill">#{p.rank||'—'}</span></button>{/each}</div><div class="pager"><button disabled={pageNumber<=1} on:click={() => navigate(`/ranking/${pageNumber-1}`)}>← Previous</button><span>Page {pageNumber}{metadata.totalPages ? ` of ${metadata.totalPages}` : ''}</span><button disabled={metadata.totalPages ? pageNumber>=metadata.totalPages : players.length<50} on:click={() => navigate(`/ranking/${pageNumber+1}`)}>Next →</button></div>{/if}</div>
<style>
.page{max-width:1400px;margin:0 auto;padding:55px 28px 70px}.heading{display:flex;justify-content:space-between;gap:30px;align-items:end;margin-bottom:25px}.eyebrow{font-size:10px;letter-spacing:.22em;color:#ef7bc3;font-weight:800}h1{font-size:48px;margin:8px 0;background:linear-gradient(90deg,#fff,#f07fc5,#9c82ff);-webkit-background-clip:text;color:transparent}p{color:#8f8d9f}.controls{display:flex;gap:9px}.controls input{height:44px;width:250px;background:#10111a;border:1px solid rgba(255,255,255,.1);border-radius:11px;color:#fff;padding:0 13px}.controls button,.pager button{height:44px;border:1px solid rgba(255,255,255,.1);background:#151622;color:#eee;border-radius:11px;padding:0 15px;cursor:pointer}.table{border:1px solid rgba(255,255,255,.08);border-radius:17px;overflow:hidden;background:linear-gradient(145deg,#11121c,#0b0c13)}.thead,.tr{display:grid;grid-template-columns:70px minmax(280px,1fr) 120px 150px 110px;align-items:center}.thead{height:48px;padding:0 20px;color:#777688;font-size:11px;text-transform:uppercase;letter-spacing:.12em}.tr{width:100%;height:68px;padding:0 20px;border:0;border-top:1px solid rgba(255,255,255,.055);background:transparent;color:#ddd;text-align:left;cursor:pointer}.tr:hover{background:rgba(255,255,255,.035)}.player{display:flex;align-items:center;gap:12px}.player img{width:38px;height:38px;border-radius:50%;object-fit:cover}.player strong{background:linear-gradient(90deg,#fff,#f28acb,#a989ff);-webkit-background-clip:text;color:transparent}.rank-pill{color:#ef85c9}.pager{display:flex;justify-content:center;align-items:center;gap:18px;margin-top:18px}.state{padding:45px;text-align:center;color:#9998a8;border:1px solid rgba(255,255,255,.08);border-radius:15px;background:#10111a}.state.error{color:#ff9dbc}.state button{margin-left:10px}@media(max-width:800px){.heading{align-items:stretch;flex-direction:column}.controls input{flex:1}.thead,.tr{grid-template-columns:45px minmax(170px,1fr) 75px 85px}.thead span:nth-child(3),.tr>span:nth-child(3){display:none}.page{padding:35px 12px}.tr,.thead{padding:0 10px}}
</style>
