<script>
	import {onMount} from 'svelte';
	import {navigate} from 'svelte-routing';
	let rows=[],loading=true,error='';
	const playersPage = 1;
	const list = x => Array.isArray(x?.data)?x.data:[];
	async function load(){loading=true;error='';try{const p=await fetch(`/api/scoresaber/v2/players?page=${playersPage}&limit=10&sort=rank&sortDirection=asc`).then(r=>r.json());const players=list(p);const batches=await Promise.all(players.slice(0,10).map(async player=>{try{const j=await fetch(`/api/scoresaber/v2/players/${player.id||player.playerId}/scores?page=1&limit=2&sort=timeset&sortDirection=desc`).then(r=>r.ok?r.json():null);return list(j).map(s=>({...s,owner:player}));}catch(_){return []}}));rows=batches.flat().sort((a,b)=>String(b.timeset||b.timeSet||'').localeCompare(String(a.timeset||a.timeSet||''))).slice(0,25);}catch(e){error=e.message||'Failed to load scores.'}finally{loading=false}}
	onMount(load);
	const map=s=>s.leaderboard||s.map||{};
	const name=s=>s.player?.name||s.player?.playerNameInGame||s.owner?.name||'Unknown';
	const mapName=s=>map(s).songName||map(s).map?.songName||s.songName||'Unknown Map';
	const accuracy=s=>Number(s.accuracy||s.acc||s.percentage||0); 
</script>
<svelte:head><title>snore saber</title></svelte:head>
<div class="page"><div class="heading"><div><span class="eyebrow">SNORE SABER SCORES</span><h1>Recent Scores</h1><p>Live score activity gathered from the current ranked field.</p></div><button class="refresh" on:click={load}>Refresh</button></div>{#if loading}<div class="state">Loading score activity…</div>{:else if error}<div class="state error">{error}<button on:click={load}>Retry</button></div>{:else}<div class="list">{#each rows as s}<button class="row" on:click={()=>navigate(`/u/${s.player?.id||s.player?.playerId||s.owner?.id}`)}><span class="avatar">{name(s)[0]}</span><span class="who"><strong>{name(s)}</strong><small>{mapName(s)}</small></span><span class="pp">{Number(s.pp||0).toFixed(2)} PP</span><span class="acc">{accuracy(s)>1?accuracy(s).toFixed(2):(accuracy(s)*100).toFixed(2)}%</span><span class="date">{s.timeset||s.timeSet||s.createdAt||''}</span></button>{/each}</div>{/if}</div>
<style>
.page{max-width:1200px;margin:0 auto;padding:55px 28px 70px}.heading{display:flex;justify-content:space-between;align-items:end;margin-bottom:25px}.eyebrow{font-size:10px;letter-spacing:.22em;color:#ef7bc3;font-weight:800}h1{font-size:48px;margin:8px 0;background:linear-gradient(90deg,#fff,#f07fc5,#9c82ff);-webkit-background-clip:text;color:transparent}p{color:#8f8d9f}.refresh,.state button{height:44px;border:1px solid rgba(255,255,255,.1);background:#151622;color:#eee;border-radius:11px;padding:0 15px;cursor:pointer}.list{border:1px solid rgba(255,255,255,.08);border-radius:17px;overflow:hidden;background:#10111a}.row{width:100%;height:74px;padding:0 20px;display:grid;grid-template-columns:40px 1fr 120px 90px 200px;gap:13px;align-items:center;background:transparent;border:0;border-top:1px solid rgba(255,255,255,.05);color:#ddd;text-align:left;cursor:pointer}.row:first-child{border-top:0}.row:hover{background:rgba(255,255,255,.035)}.avatar{width:36px;height:36px;border-radius:50%;display:grid;place-items:center;background:linear-gradient(135deg,#ef72bb,#8f78ff);font-weight:900}.who{min-width:0}.who strong,.who small{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.who strong{background:linear-gradient(90deg,#fff,#f28acb,#a989ff);-webkit-background-clip:text;color:transparent}.who small{font-size:11px;color:#888797;margin-top:4px}.pp{color:#ddd}.acc{color:#ef86c9}.date{font-size:11px;color:#777688;overflow:hidden;text-overflow:ellipsis}.state{padding:45px;text-align:center;color:#9998a8;border:1px solid rgba(255,255,255,.08);border-radius:15px;background:#10111a}.error{color:#ff9dbc}@media(max-width:800px){.row{grid-template-columns:40px 1fr 80px}.row .date{display:none}.row .pp{font-size:11px}.page{padding:35px 12px}}
</style>
