<script>
		import {navigate} from 'svelte-routing';
	let maps=[],metadata={},page=1,search='',loading=true,error='';
	async function load(){loading=true;error='';try{const r=await fetch(`/api/scoresaber/v2/maps?page=${page}&limit=24&sort=plays&sortDirection=desc${search?`&search=${encodeURIComponent(search)}`:''}`);if(!r.ok)throw Error(`ScoreSaber returned ${r.status}`);const j=await r.json();maps=Array.isArray(j?.data)?j.data:[];metadata=j?.metadata||{};}catch(e){error=e.message||'Failed to load maps.'}finally{loading=false}}
	let loadedPage = 0;
	$: if (page !== loadedPage) { loadedPage = page; load(); }
	function mapName(m){return m.songName||m.name||'Unknown Map'}
</script>
<svelte:head><title>snore saber</title></svelte:head>
<div class="page"><div class="heading"><div><span class="eyebrow">SNORE SABER MAPS</span><h1>Explore Maps</h1><p>Ranked, qualified and loved Beat Saber maps from the live ScoreSaber index.</p></div><div class="controls"><input bind:value={search} on:keydown={(e)=>e.key==='Enter'&&load()} placeholder="Search maps…" /><button on:click={load}>Search</button></div></div>
{#if loading}<div class="state">Loading live maps…</div>{:else if error}<div class="state error">{error}<button on:click={load}>Retry</button></div>{:else}<div class="cards">{#each maps as m}<button class="card" on:click={() => m.id && navigate('/maps')}>{#if m.coverUrl || m.coverImage}<img src={m.coverUrl||m.coverImage} alt="" />{:else}<div class="cover">♪</div>{/if}<div class="card-copy"><div class="title">{mapName(m)}</div><div class="sub">{m.songSubName||''}</div><div class="meta">{m.levelAuthorName||'Unknown mapper'} · {Number(m.stars||m.realm?.stars||0).toFixed(2)}★</div><div class="plays">{Number(m.plays||m.totalScores||0).toLocaleString()} plays</div></div></button>{/each}</div><div class="pager"><button disabled={page<=1} on:click={()=>page--}>← Previous</button><span>Page {page}{metadata.totalPages?` of ${metadata.totalPages}`:''}</span><button disabled={metadata.totalPages?page>=metadata.totalPages:maps.length<24} on:click={()=>page++}>Next →</button></div>{/if}</div>
<style>
.page{max-width:1400px;margin:0 auto;padding:55px 28px 70px}.heading{display:flex;justify-content:space-between;align-items:end;gap:25px;margin-bottom:26px}.eyebrow{font-size:10px;letter-spacing:.22em;color:#ef7bc3;font-weight:800}h1{font-size:48px;margin:8px 0;background:linear-gradient(90deg,#fff,#f07fc5,#9c82ff);-webkit-background-clip:text;color:transparent}p{color:#8f8d9f}.controls{display:flex;gap:9px}.controls input{height:44px;width:260px;background:#10111a;border:1px solid rgba(255,255,255,.1);border-radius:11px;color:#fff;padding:0 13px}.controls button,.pager button{height:44px;border:1px solid rgba(255,255,255,.1);background:#151622;color:#eee;border-radius:11px;padding:0 15px;cursor:pointer}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:15px}.card{min-width:0;display:flex;gap:13px;text-align:left;padding:12px;border:1px solid rgba(255,255,255,.08);border-radius:15px;background:linear-gradient(145deg,#11121c,#0b0c13);color:#fff;cursor:pointer}.card:hover{transform:translateY(-1px);border-color:rgba(239,114,187,.25)}.card img,.cover{width:82px;height:82px;flex:0 0 82px;object-fit:cover;border-radius:10px}.cover{display:grid;place-items:center;background:linear-gradient(135deg,#2c1c3e,#171a3a);font-size:28px;color:#ef83c6}.card-copy{min-width:0}.title{font-weight:800;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;background:linear-gradient(90deg,#fff,#f28acb,#a989ff);-webkit-background-clip:text;color:transparent}.sub,.meta{white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.sub{font-size:11px;color:#7f7d8e;margin-top:2px}.meta{font-size:11px;color:#a9a6b5;margin-top:14px}.plays{font-size:10px;color:#ef85c9;margin-top:7px}.pager{display:flex;justify-content:center;gap:18px;align-items:center;margin-top:20px}.state{padding:45px;text-align:center;color:#9998a8;border:1px solid rgba(255,255,255,.08);border-radius:15px;background:#10111a}.error{color:#ff9dbc}.state button{margin-left:10px}@media(max-width:1000px){.cards{grid-template-columns:1fr 1fr}}@media(max-width:650px){.heading{flex-direction:column;align-items:stretch}.controls input{flex:1}.cards{grid-template-columns:1fr}.page{padding:35px 12px}}
</style>
