<script>
	import {onMount} from 'svelte';
	import {navigate} from 'svelte-routing';
	export let initialPlayerId;
	let player=null,scores=[],loading=true,error='';
	async function load(){loading=true;error='';try{const [p,s]=await Promise.all([fetch(`/api/scoresaber/v2/players/${encodeURIComponent(initialPlayerId)}`).then(r=>r.ok?r.json():Promise.reject(Error(`Player returned ${r.status}`))),fetch(`/api/scoresaber/v2/players/${encodeURIComponent(initialPlayerId)}/scores?page=1&limit=20&sort=score&sortDirection=desc`).then(r=>r.ok?r.json():null)]);player=p;scores=Array.isArray(s?.data)?s.data:[];}catch(e){error=e.message||'Could not load player.'}finally{loading=false}}
	onMount(load);
	const map=s=>s.leaderboard||s.map||{};
</script>
<svelte:head><title>snore saber</title></svelte:head>
<div class="page">{#if loading}<div class="state">Loading player…</div>{:else if error}<div class="state error">{error}<button on:click={load}>Retry</button></div>{:else if player}<section class="profile"><div class="profile-top"><img src={player.avatar||player.avatarUrl||'/assets/snoresaber-icon.png'} alt="" /><div><span class="eyebrow">SCORE SABER PLAYER</span><h1>{player.name||player.playerNameInGame}</h1><p>{player.country||'Unknown country'} · #{player.rank||player.stats?.rank||'—'}</p></div></div><div class="stats"><div><b>{Number(player.pp||player.stats?.pp||0).toFixed(2)}</b><small>PP</small></div><div><b>#{player.rank||player.stats?.rank||'—'}</b><small>Global rank</small></div><div><b>{Number(player.totalScore||player.stats?.totalScore||0).toLocaleString()}</b><small>Total score</small></div><div><b>{Number(player.totalPlayCount||player.stats?.totalPlayCount||0).toLocaleString()}</b><small>Plays</small></div></div></section><section class="scores"><header><h2>Best Scores</h2><button on:click={()=>navigate('/scores/1')}>All Scores →</button></header>{#each scores as s}<div class="score"><div class="cover">{#if map(s).coverUrl||map(s).coverImage}<img src={map(s).coverUrl||map(s).coverImage} alt="" />{:else}♪{/if}</div><div class="song"><strong>{map(s).songName||s.songName||'Unknown Map'}</strong><small>{map(s).songSubName||''} · {map(s).levelAuthorName||'Unknown mapper'}</small></div><div><b>{Number(s.pp||0).toFixed(2)} PP</b><small>{Number(s.accuracy||s.acc||0).toFixed(2)}%</small></div><div class="score-rank">#{s.rank||'—'}</div></div>{/each}</section>{/if}</div>
<style>
.page{max-width:1200px;margin:0 auto;padding:55px 28px 70px}.profile{padding:28px;border:1px solid rgba(255,255,255,.08);border-radius:20px;background:linear-gradient(145deg,#11121c,#0b0c13)}.profile-top{display:flex;gap:20px;align-items:center}.profile-top img{width:92px;height:92px;border-radius:50%;object-fit:cover}.eyebrow{font-size:10px;letter-spacing:.22em;color:#ef7bc3;font-weight:800}h1{font-size:43px;margin:8px 0;background:linear-gradient(90deg,#fff,#f07fc5,#9c82ff);-webkit-background-clip:text;color:transparent}.profile p{color:#888797}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-top:25px}.stats div{padding:17px;border-radius:13px;background:rgba(255,255,255,.03);border:1px solid rgba(255,255,255,.06)}.stats b,.stats small{display:block}.stats small{color:#7e7c8c;font-size:10px;margin-top:5px}.scores{margin-top:20px;border:1px solid rgba(255,255,255,.08);border-radius:17px;background:#10111a;overflow:hidden}.scores header{display:flex;justify-content:space-between;padding:18px 20px}.scores h2{margin:0}.scores header button{border:0;background:none;color:#ef7dc6;font-weight:800}.score{display:grid;grid-template-columns:58px 1fr 120px 70px;align-items:center;gap:13px;padding:11px 20px;border-top:1px solid rgba(255,255,255,.05)}.cover img,.cover{width:58px;height:58px;border-radius:8px;object-fit:cover}.cover{display:grid;place-items:center;background:#211a34;color:#ef83c6}.song strong,.song small,.score>div:nth-child(3) small{display:block}.song strong{background:linear-gradient(90deg,#fff,#f28acb,#a989ff);-webkit-background-clip:text;color:transparent}.song small,.score>div:nth-child(3) small{font-size:10px;color:#7d7b8c;margin-top:4px}.score-rank{color:#ef86c9}.state{padding:45px;text-align:center;color:#9998a8;border:1px solid rgba(255,255,255,.08);border-radius:15px;background:#10111a}.error{color:#ff9dbc}.state button{margin-left:10px}@media(max-width:700px){.page{padding:35px 12px}.stats{grid-template-columns:1fr 1fr}.score{grid-template-columns:48px 1fr 80px}.score-rank{display:none}.cover img,.cover{width:48px;height:48px}.profile-top img{width:72px;height:72px}h1{font-size:31px}}
</style>
