-- Legacy safety note: SnoreSaber is no longer limited to six maps.
-- Do not run a hard-coded map prune against the production database.
-- Use the admin map workflow or the importer with an explicit keep list instead.
