CREATE TABLE IF NOT EXISTS players (
  id BIGSERIAL PRIMARY KEY,
  steam_id VARCHAR(32) UNIQUE NOT NULL,
  username VARCHAR(64) NOT NULL,
  avatar_url TEXT,
  country VARCHAR(8),
  pp DOUBLE PRECISION NOT NULL DEFAULT 0,
  rank INTEGER,
  total_score BIGINT NOT NULL DEFAULT 0,
  play_count INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS maps (
  id BIGSERIAL PRIMARY KEY,
  hash VARCHAR(64) UNIQUE NOT NULL,
  song_name TEXT NOT NULL,
  mapper TEXT,
  difficulty VARCHAR(32) NOT NULL,
  characteristic VARCHAR(64),
  stars DOUBLE PRECISION NOT NULL DEFAULT 0,
  ranked BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS scores (
  id BIGSERIAL PRIMARY KEY,
  player_id BIGINT NOT NULL REFERENCES players(id) ON DELETE CASCADE,
  map_id BIGINT NOT NULL REFERENCES maps(id) ON DELETE CASCADE,
  score INTEGER NOT NULL,
  accuracy DOUBLE PRECISION NOT NULL,
  pp DOUBLE PRECISION NOT NULL DEFAULT 0,
  modifiers TEXT[] NOT NULL DEFAULT '{}',
  max_combo INTEGER,
  misses INTEGER,
  full_combo BOOLEAN NOT NULL DEFAULT FALSE,
  played_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_scores_player ON scores(player_id);
CREATE INDEX IF NOT EXISTS idx_scores_map ON scores(map_id);
CREATE INDEX IF NOT EXISTS idx_scores_pp ON scores(pp DESC);

CREATE TABLE IF NOT EXISTS score_history (
  id BIGSERIAL PRIMARY KEY,
  player_id BIGINT NOT NULL REFERENCES players(id) ON DELETE CASCADE,
  score_id BIGINT REFERENCES scores(id) ON DELETE SET NULL,
  pp DOUBLE PRECISION NOT NULL,
  recorded_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS clans (
  id BIGSERIAL PRIMARY KEY,
  name VARCHAR(64) UNIQUE NOT NULL,
  tag VARCHAR(16) UNIQUE NOT NULL,
  owner_player_id BIGINT REFERENCES players(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS clan_members (
  clan_id BIGINT NOT NULL REFERENCES clans(id) ON DELETE CASCADE,
  player_id BIGINT NOT NULL REFERENCES players(id) ON DELETE CASCADE,
  joined_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (clan_id, player_id)
);

CREATE TABLE IF NOT EXISTS events (
  id BIGSERIAL PRIMARY KEY,
  name VARCHAR(128) NOT NULL,
  description TEXT,
  starts_at TIMESTAMPTZ,
  ends_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);