<Project>
  <PropertyGroup>
    <RepositoryRoot>$(MSBuildThisFileDirectory)</RepositoryRoot>
    <LangVersion>latestmajor</LangVersion>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <CodeAnalysisTreatWarningsAsErrors>true</CodeAnalysisTreatWarningsAsErrors>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(GITHUB_ACTIONS)' == 'true'">true</ContinuousIntegrationBuild>
  </PropertyGroup>
  <Import Project="$(MSBuildThisFileDirectory)Directory.Build.local.props" Condition="Exists('$(MSBuildThisFileDirectory)Directory.Build.local.props')" />
  <PropertyGroup>
    <SnoreSaberWebsiteBaseUrl Condition="'$(SnoreSaberWebsiteBaseUrl)' == ''">https://snoresaber.vercel.app</SnoreSaberWebsiteBaseUrl>
    <SnoreSaberApiBaseUrl Condition="'$(SnoreSaberApiBaseUrl)' == ''">https://snoresaber.vercel.app</SnoreSaberApiBaseUrl>
    <SnoreSaberCdnBaseUrl Condition="'$(SnoreSaberCdnBaseUrl)' == ''">https://cdn.saberrank.local</SnoreSaberCdnBaseUrl>
    <SnoreSaberLudusUrl Condition="'$(SnoreSaberLudusUrl)' == ''">wss://ludus-1.saberrank.local/v1/connect</SnoreSaberLudusUrl>
  </PropertyGroup>
</Project>
